[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "netzoopy-stoat"
authors = [
    {name = "Ladislav Hovan", email = "ladislav.hovan@ncmbm.uio.no"},
]
dynamic = ["version"]
description = """A package to generate spatially resolved gene \
    regulatory networks from spatial transcriptomics data."""
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["transcription-factors", "gene-regulatory-network"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "anndata>=0.12.0,<0.13",
    "gseapy>=1.1.13,<2",
    "hdbscan>=0.8.0,<0.9",
    "matplotlib>=3.5.0,<4",
    "netZooPy>=0.10.0,<0.12",
    "numpy>=2.2.0,<2.5",
    "ome_zarr>=0.13.0,<0.14",
    "pandas>=2.0.0,<3",
    "scanpy>=1.10.0,<2",
    "setuptools>=70.0.0,<80.10.0",  # Hidden dependency of netZooPy
    "spagcn>=1.2.0,<2",
    "spatialdata>=0.7.2,<0.8",
    "spatialdata-io>=0.6.0,<0.7",
    "spatialdata-plot>=0.3.0,<0.5",
    "squidpy>=1.8.2,<2",
    "torch>=2.0.0,<3",
]

[project.scripts]
netzoopy-stoat = "stoat.cli:cli"

[project.urls]
Repository = "https://github.com/ladislav-hovan/stoat"

[tool.setuptools_scm]
version_scheme = "only-version"
local_scheme = "no-local-version"

[tool.pytest.ini_options]
filterwarnings = ["ignore:pkg_resources is deprecated as an API"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.tasks]
stoat = "netzoopy-stoat"

[tool.pixi.dependencies]
python = "3.11.*"

[tool.pixi.pypi-dependencies]
netzoopy-stoat = { path = ".", editable = true }

[tool.pixi.environments]
stoat-dev = ["stoat-dev"]
stoat-gpu = ["stoat-gpu"]
stoat-ipython = ["stoat-ipython"]

[tool.pixi.feature.stoat-dev.dependencies]
pytest = ">=8.0.0"

[tool.pixi.feature.stoat-dev.tasks]
test = "pytest"

[tool.pixi.feature.stoat-gpu.pypi-dependencies]
cupy-cuda12x = ">=12.0.0"

[tool.pixi.feature.stoat-gpu.tasks]
stoat-gpu = "netzoopy-stoat"

[tool.pixi.feature.stoat-ipython.pypi-dependencies]
ipykernel = ">=7.0.0"
ipython = ">=9.0.0"
notebook = ">=7.0.0"
pip = ">=25.0.0"
