# Copyright (C) 2025 Ladislav Hovan <ladislav.hovan@ncmbm.uio.no>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This library is free software: you can redistribute it and/or
# modify it under the terms of the GNU Public License as published
# by the Free Software Foundation; either version 3 of the License,
# or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Public License along
# with this library. If not, see <https://www.gnu.org/licenses/>.

### Imports ###
import inspect
import os.path
import typing

import numpy as np
import pandas as pd
import squidpy as sq

from anndata import AnnData
from biomart import BiomartServer
from functools import wraps
from io import BytesIO
from netZooPy.panda.panda import Panda
from pathlib import Path
from spatialdata_io import visium, visium_hd
from spatialdata import SpatialData
from typing import Iterable, List, Optional, Tuple, Union

from stoat.config import *
from stoat.modules.expression_smoother import ExpressionSmoother
from stoat.modules.plotting import *
from stoat.modules.region_assigner import RegionAssigner
from stoat.modules.utils import weigh_by_distance

### Class definition ###
class Stoat:
    ### Initialisation ###
    def __init__(
        self,
    ) -> None:

        # TODO: Implement network methods other than PANDA (PUMA, DRAGON?)

        # Variables generated by the class
        self.spatial = None

    ### Methods ###
    # TODO: Adjust the function signature (return None)
    # and documentation (format, type hints)
    @wraps(visium)
    def load_visium_dataset(
        self,
        *args,
        **kwargs,
    ) -> None:

        self.spatial = visium(*args, **kwargs)


    @wraps(visium_hd)
    def load_visium_hd_dataset(
        self,
        *args,
        **kwargs,
    ) -> None:

        self.spatial = visium_hd(*args, **kwargs)


    def average_expression(
        self,
        n_rings: int = 1,
        max_invalid: int = 0,
        edges_invalid: bool = True,
        avg_function: Callable = weigh_by_distance,
        *args,
        **kwargs,
    ) -> None:

        smoother = ExpressionSmoother(self.spatial['table'], n_rings)
        if edges_invalid:
            smoother.filter_edges()
        smoother.enforce_max_invalid(max_invalid)
        smoother.smooth_expression(avg_function, *args, **kwargs)


    def assign_regions(
        self,
        mapping: Optional[pd.Series] = None,
    ) -> None:

        assigner = RegionAssigner(self.spatial)
        assigner.assign_regions(mapping)


    def calculate_networks(
        self,
        save_dir: Path = './',
        motif_prior: Optional[Union[Path, pd.DataFrame]] = None,
        ppi_prior: Optional[Union[Path, pd.DataFrame]] = None,
        extension: EXTENSION = 'feather',
    ) -> None:

        pass