name: STOAT test on latest Ubuntu and Python 3.8

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  sponge-test:        
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Check Python version
      run: |
        which python3
        python3 --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .

    - name: Run the tests
      run: pytest tests
