name: STOAT tests

on:
  push:
    branches:
    - devel
  pull_request:
    branches:
    - main
    - devel
  schedule:
  - cron: '30 3 1 * *'  # 1st of every month at 3:30
  workflow_dispatch:

jobs:
  os-python-compatibility:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        python: [ '3.11', '3.12', '3.13' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Mac-specific setup
      if: matrix.os == 'macos-latest'
      run: brew install hdf5

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}

    - name: Check Python version
      run: |
        which python3
        python3 --version

    - name: Install dependencies on Mac
      if: matrix.os == 'macos-latest'
      env:
        # Bypass errors for Python versions
        CFLAGS: '-Wno-error=uninitialized-const-pointer -Wno-error=default-const-init-var-unsafe'
        CXXFLAGS: '-Wno-error=uninitialized-const-pointer -Wno-error=default-const-init-var-unsafe'
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .

    - name: Install dependencies on other systems
      if: matrix.os != 'macos-latest'
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .

    - name: Run the tests
      run: pytest tests
